# 时钟: 50MHz 输入.
set_property PACKAGE_PIN U22 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 20.000 -name sys_clk [get_ports clk]

# KEY1/MENU -> 低电平复位.
set_property PACKAGE_PIN M4 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PULLUP true [get_ports rst_n]

# LED0..LED7, 板载低电平点亮 (引脚参考板级 sw_led 工程).
set_property PACKAGE_PIN N17 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN M19 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN P16 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN N16 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN N19 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN P19 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN N24 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN N23 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]

# 7 段数码管位选 seg_digit[5:0], 低电平有效 (引脚参考板级 sw_seg 工程).
set_property PACKAGE_PIN R16 [get_ports {seg_digit[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_digit[0]}]
set_property PACKAGE_PIN R17 [get_ports {seg_digit[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_digit[1]}]
set_property PACKAGE_PIN N18 [get_ports {seg_digit[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_digit[2]}]
set_property PACKAGE_PIN K25 [get_ports {seg_digit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_digit[3]}]
set_property PACKAGE_PIN R25 [get_ports {seg_digit[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_digit[4]}]
set_property PACKAGE_PIN T24 [get_ports {seg_digit[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_digit[5]}]

# 7 段数码管段 seg[7:0], 共阳极低电平点亮. seg[7]=DP .. seg[0]=PA.
set_property PACKAGE_PIN K26 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN M20 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN L20 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN N21 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN N22 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN P21 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN P23 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property PACKAGE_PIN P24 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]

# UART TX -> WCH USB 转串口 (L18), 115200-8N1. 只发不收, RX 引脚本工程不占.
set_property PACKAGE_PIN L18 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]

# FTDI 端口 1 的独立 RISC-V JTAG. 端口 0 仍留给 Xilinx 配置 JTAG.
set_property PACKAGE_PIN M21 [get_ports cpu_ttck]
set_property PACKAGE_PIN L22 [get_ports cpu_ttdi]
set_property PACKAGE_PIN L24 [get_ports cpu_ttdo]
set_property PACKAGE_PIN L23 [get_ports cpu_ttms]
set_property PACKAGE_PIN M25 [get_ports cpu_trtck]
set_property PACKAGE_PIN M24 [get_ports cpu_trst_n]
set_property PACKAGE_PIN L25 [get_ports cpu_tsrst_n]
set_property IOSTANDARD LVCMOS33 [get_ports {cpu_ttck cpu_ttdi cpu_ttdo cpu_ttms cpu_trtck cpu_trst_n cpu_tsrst_n}]
set_property PULLUP true [get_ports {cpu_ttck cpu_ttdi cpu_ttms cpu_trst_n cpu_tsrst_n}]
set_property DRIVE 8 [get_ports {cpu_ttdo cpu_trtck}]
set_property SLEW SLOW [get_ports {cpu_ttdo cpu_trtck}]

# JTAG 自带异步时钟和 CDC,不让系统时钟分析跨域端口路径.
set_false_path -from [get_ports {cpu_ttck cpu_ttdi cpu_ttms cpu_trst_n}]
set_false_path -to [get_ports {cpu_ttdo cpu_trtck}]
