# 外部 SRAM 顶层约束. 公共板级 I/O 由流程同时加载 constr/top.xdc.

# 地址 A[18:0], 两片共用. 映射来自 fpga_100t/sram 已验证工程.
set_property PACKAGE_PIN E26 [get_ports {sram_addr[0]}]
set_property PACKAGE_PIN E25 [get_ports {sram_addr[1]}]
set_property PACKAGE_PIN D26 [get_ports {sram_addr[2]}]
set_property PACKAGE_PIN D25 [get_ports {sram_addr[3]}]
set_property PACKAGE_PIN G22 [get_ports {sram_addr[4]}]
set_property PACKAGE_PIN H18 [get_ports {sram_addr[5]}]
set_property PACKAGE_PIN M15 [get_ports {sram_addr[6]}]
set_property PACKAGE_PIN M16 [get_ports {sram_addr[7]}]
set_property PACKAGE_PIN L15 [get_ports {sram_addr[8]}]
set_property PACKAGE_PIN K23 [get_ports {sram_addr[9]}]
set_property PACKAGE_PIN J25 [get_ports {sram_addr[10]}]
set_property PACKAGE_PIN K22 [get_ports {sram_addr[11]}]
set_property PACKAGE_PIN H26 [get_ports {sram_addr[12]}]
set_property PACKAGE_PIN J26 [get_ports {sram_addr[13]}]
set_property PACKAGE_PIN J24 [get_ports {sram_addr[14]}]
set_property PACKAGE_PIN G25 [get_ports {sram_addr[15]}]
set_property PACKAGE_PIN G24 [get_ports {sram_addr[16]}]
set_property PACKAGE_PIN J21 [get_ports {sram_addr[17]}]
set_property PACKAGE_PIN J23 [get_ports {sram_addr[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[*]}]
set_property DRIVE 8 [get_ports {sram_addr[*]}]
set_property SLEW FAST [get_ports {sram_addr[*]}]

# 数据 DQ[31:0], 低 16 位属于 SRAM0, 高 16 位属于 SRAM1.
set_property PACKAGE_PIN U21 [get_ports {sram_dq[0]}]
set_property PACKAGE_PIN U25 [get_ports {sram_dq[1]}]
set_property PACKAGE_PIN W26 [get_ports {sram_dq[2]}]
set_property PACKAGE_PIN Y26 [get_ports {sram_dq[3]}]
set_property PACKAGE_PIN AA25 [get_ports {sram_dq[4]}]
set_property PACKAGE_PIN AB26 [get_ports {sram_dq[5]}]
set_property PACKAGE_PIN AA24 [get_ports {sram_dq[6]}]
set_property PACKAGE_PIN AB24 [get_ports {sram_dq[7]}]
set_property PACKAGE_PIN AC24 [get_ports {sram_dq[8]}]
set_property PACKAGE_PIN AC26 [get_ports {sram_dq[9]}]
set_property PACKAGE_PIN AB25 [get_ports {sram_dq[10]}]
set_property PACKAGE_PIN Y23 [get_ports {sram_dq[11]}]
set_property PACKAGE_PIN Y25 [get_ports {sram_dq[12]}]
set_property PACKAGE_PIN W25 [get_ports {sram_dq[13]}]
set_property PACKAGE_PIN V26 [get_ports {sram_dq[14]}]
set_property PACKAGE_PIN U26 [get_ports {sram_dq[15]}]
set_property PACKAGE_PIN T14 [get_ports {sram_dq[16]}]
set_property PACKAGE_PIN T17 [get_ports {sram_dq[17]}]
set_property PACKAGE_PIN W18 [get_ports {sram_dq[18]}]
set_property PACKAGE_PIN U17 [get_ports {sram_dq[19]}]
set_property PACKAGE_PIN V18 [get_ports {sram_dq[20]}]
set_property PACKAGE_PIN T18 [get_ports {sram_dq[21]}]
set_property PACKAGE_PIN W19 [get_ports {sram_dq[22]}]
set_property PACKAGE_PIN T19 [get_ports {sram_dq[23]}]
set_property PACKAGE_PIN W21 [get_ports {sram_dq[24]}]
set_property PACKAGE_PIN Y22 [get_ports {sram_dq[25]}]
set_property PACKAGE_PIN Y21 [get_ports {sram_dq[26]}]
set_property PACKAGE_PIN U20 [get_ports {sram_dq[27]}]
set_property PACKAGE_PIN T20 [get_ports {sram_dq[28]}]
set_property PACKAGE_PIN W20 [get_ports {sram_dq[29]}]
set_property PACKAGE_PIN Y20 [get_ports {sram_dq[30]}]
set_property PACKAGE_PIN V19 [get_ports {sram_dq[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[*]}]
set_property DRIVE 8 [get_ports {sram_dq[*]}]
set_property SLEW FAST [get_ports {sram_dq[*]}]

set_property PACKAGE_PIN F25 [get_ports sram0_ce_n]
set_property PACKAGE_PIN E23 [get_ports sram1_ce_n]
set_property PACKAGE_PIN H23 [get_ports sram0_oe_n]
set_property PACKAGE_PIN F23 [get_ports sram1_oe_n]
set_property PACKAGE_PIN L19 [get_ports sram0_we_n]
set_property PACKAGE_PIN J18 [get_ports sram1_we_n]
set_property PACKAGE_PIN G26 [get_ports sram0_lb_n]
set_property PACKAGE_PIN H24 [get_ports sram0_ub_n]
set_property PACKAGE_PIN K20 [get_ports sram1_lb_n]
set_property PACKAGE_PIN F24 [get_ports sram1_ub_n]
set_property IOSTANDARD LVCMOS33 [get_ports {sram0_ce_n sram1_ce_n sram0_oe_n sram1_oe_n sram0_we_n sram1_we_n sram0_lb_n sram0_ub_n sram1_lb_n sram1_ub_n}]
set_property DRIVE 8 [get_ports {sram0_ce_n sram1_ce_n sram0_oe_n sram1_oe_n sram0_we_n sram1_we_n sram0_lb_n sram0_ub_n sram1_lb_n sram1_ub_n}]
set_property SLEW FAST [get_ports {sram0_ce_n sram1_ce_n sram0_oe_n sram1_oe_n sram0_we_n sram1_we_n sram0_lb_n sram0_ub_n sram1_lb_n sram1_ub_n}]

# SRAM DQ 是异步器件输出, 没有 FPGA 发起时钟. 控制器以 50MHz 三拍时序保证采样余量.
set_false_path -from [get_ports {sram_dq[*]}]
